Adding envs for ns scope and argo's container runtime executor.
litmuschaos/litmus-helm pull request #106
Opened 2021-04-18 02:59 UTC by ishangupta-ds

Signed-off-by: ishangupta-ds <ishan@chaosnative.com>

#### What this PR does / why we need it:

* This PR adds environment variables for litmus 2.0 server
- `PORTAL_ENDPOINT` for the graphql server endpoint to be used in namespaced mode of portal installation. 
   > Defaults to `http://litmusportal-server-service:9002`
- `CONTAINER_RUNTIME_EXECUTOR` for tuning argo workflow controller's CNE
   > Defaults to `k8sapi`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

@ksatchit @rajdas98 @ispeakc0de @Jasstkn

2021-04-18 03:18 UTC, ishangupta-ds commented
@rajdas98 @ksatchit PTAL

2021-04-18 05:40 UTC, Jasstkn approved these changes

2021-04-18 09:31 UTC, ispeakc0de approved these changes

2021-04-19 13:17 UTC, rajdas98 requested changes
Sync the server-role.yml with namespace-k8s-manifest.yml

2021-04-19 14:31 UTC, ishangupta-ds commented
sure @rajdas98

2021-04-20 09:33 UTC, rajdas98 commented
@ishangupta-ds Is this PR good to merge?

2021-04-20 11:20 UTC, ishangupta-ds commented
> @ishangupta-ds Is this PR good to merge?

yes @rajdas98 we have tested all features its good to merge.

2021-04-20 11:40 UTC, rajdas98 approved these changes

2021-04-20 11:40 UTC, merged