Use the right value for the host
litmuschaos/litmus-helm pull request #112
Opened 2021-04-22 05:23 UTC by rberrelleza

Signed-off-by: Ramiro Berrelleza <rberrelleza@gmail.com>

#### What this PR does / why we need it:
Pass the value of the host to the ingress
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2021-04-22 08:19 UTC, Jasstkn reviewed
Hi! Why do we need this change? Is passing hosts to the values doesn't work?

2021-04-22 08:25 UTC, rajdas98 approved these changes

2021-04-22 20:05 UTC, rberrelleza commented
@Jasstkn not today, the value in .Values.ingress.host is ignored by the chart, that's the motivation with with my PR.

2021-04-23 11:12 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/templates/ingress.yaml
> +  - host: {{ .Values.ingress.host | quote }}
usually host is a list. so it's better to iterate over it like that:
```
{{- range .Values.ingress.host }}
```
and then use the value like that:
```
  - host: {{ .host | quote }}
    http:
```

Does it make sense for you?

2021-04-23 16:11 UTC, rberrelleza commented on charts/litmus-2-0-0-beta/templates/ingress.yaml
> +  - host: {{ .Values.ingress.host | quote }}
I agree, that's a pattern that several charts follow. The problem here is that  `.Values.ingress.host` today is not a list, but a string, so this would be a breaking change. This PR fixes the current behavior, but doesn't introduce a breaking change.

2021-04-23 18:34 UTC, Jasstkn requested changes
Could you fix the CI then?
```
 ✖︎ litmus-2-0-0-beta => (version: "2.0.14-Beta4", path: "charts/litmus-2-0-0-beta") > Chart version not ok. Needs a version bump!
```

2021-04-23 20:20 UTC, rberrelleza commented
> Could you fix the CI then?
> 
> ```
>  ✖︎ litmus-2-0-0-beta => (version: "2.0.14-Beta4", path: "charts/litmus-2-0-0-beta") > Chart version not ok. Needs a version bump!
> ```

fixed!

2021-04-24 06:07 UTC, Jasstkn approved these changes

2021-04-24 06:07 UTC, merged