Adds support for Openshift Route
litmuschaos/litmus-helm pull request #114
Opened 2021-04-29 11:09 UTC by radudd

Added support for exposing Frontend Service using OpenShift Routes

Signed-off-by: Radu Domnu <radu.domnu@gmail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2021-04-30 09:42 UTC, Jasstkn requested changes
Thank you for your contribution! I've left some comments.

2021-04-30 09:42 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/templates/frontend-route.yaml
> +
extra line here

2021-04-30 09:42 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/values.yaml
> +# OpenShift Route
Can we declare something like openshift and inside it put route? I think it could be more clear for users to understand if they should configure this parameter or not. Does it make sense?

2021-04-30 13:53 UTC, radudd commented on charts/litmus-2-0-0-beta/values.yaml
> +# OpenShift Route
Done

2021-04-30 13:54 UTC, radudd commented on charts/litmus-2-0-0-beta/templates/frontend-route.yaml
> +
done

2021-04-30 14:14 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/values.yaml
> +# OpenShift Route
Let's just put openshift specific configuration under that with some explanation like this:

```
# Openshift specific configuration
openshift:
  # <explain use case>
  route: 
```

2021-05-03 14:55 UTC, ksatchit approved these changes

2021-05-03 14:56 UTC, ksatchit commented
Looks good, though the chart might need to be updated - beta is flying thick and fast. Sorry about that @radudd !

2021-05-03 16:21 UTC, radudd commented
> Looks good, though the chart might need to be updated - beta is flying thick and fast. Sorry about that @radudd !

No worries, bumped to Beta5

2021-05-07 10:31 UTC, rajdas98 approved these changes

2021-05-07 10:33 UTC, ispeakc0de approved these changes

2021-05-07 10:34 UTC, merged