Add required security context to mongo pod
litmuschaos/litmus-helm pull request #141
Opened 2021-07-12 02:24 UTC by Niksko

This pod runs as root, and requires CHOWN, SETUID and SETGID to work
properly. These should be declared on the security context of the
pod/container in order for the correct PSP to be selected at admission
time, if in use.

Signed-off-by: Nikolas Skoufis <nskoufis@seek.com.au>

@Jasstkn 
@rajdas98 
@ispeakc0de 

#### What this PR does / why we need it:
Adds security context parameters required when using a PSP

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #140 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2021-07-12 12:10 UTC, Jasstkn approved these changes
Hi! Thank you for your contribution! 
I don't have any objections regarding that. Approved.

2021-07-19 13:20 UTC, rajdas98 requested changes

2021-07-19 13:20 UTC, rajdas98 commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +      securityContext:
Can you put this in values.yaml?

2021-07-19 13:20 UTC, rajdas98 commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +          securityContext:
Same here

2022-10-26 06:17 UTC, Jasstkn commented
Hey. I'm going to close that one because we added support for bitnami mongodb or you can use your own mongo instance and configure it properly according to the requirements.

2022-10-26 06:17 UTC, closed without merging