Support for limit / request resource values ​​in mongo and authServer
litmuschaos/litmus-helm pull request #142
Opened 2021-07-13 12:33 UTC by Vr00mm

Support for limit / request resource values ​​in mongo and server (authServer) templates

Signed-off-by: Rémi ZIOLKOWSKI <remi.ziolkowski-ext@pole-emploi.fr>

#### What this PR does / why we need it:
This PR permit to set or limit ressources for authServer ( container of server-deployment.yml ) and for mongo ( container of mongo-sts.yml ) 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

2021-07-13 12:35 UTC, rajdas98 requested changes

2021-07-13 12:35 UTC, rajdas98 commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +          resources:
Can you add an if condition for checking non-empty resources?

2021-07-13 12:35 UTC, rajdas98 commented on charts/litmus-2-0-0-beta/templates/server-deployment.yaml
> +          resources:
same here

2021-07-13 12:45 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +          resources:
Hello Raj, Yes i can. But we need it ?
https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus-2-0-0-beta/values.yaml#L45

Or I should add the same condition for the frontend and graphServer templates ?

2021-07-13 13:00 UTC, rajdas98 commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +          resources:
>Hello Raj, Yes i can. But we need it ?
https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus-2-0-0-beta/values.yaml#L45

Okay, then it's not required

> Or I should add the same condition for the frontend and graphServer templates ?

Yes, please.

BTW thanks for this contribution.

2021-07-13 15:44 UTC, rajdas98 approved these changes

2021-07-13 15:45 UTC, rajdas98 commented
@Vr00mm circleci build is failed.

2021-07-13 16:20 UTC, Vr00mm commented
> @Vr00mm circleci build is failed.

Iam not in :)
"ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-control-plane cat /kind/version" failed with error: exit status 126"

2021-07-13 16:33 UTC, Vr00mm commented
I writted some more code for {live,readi}-nessProbes and  Strategy.rollingUpdate
Ill push another PR tomorow.

See you later,
Best regards

2021-07-16 12:04 UTC, Vr00mm commented
Hello, can @ispeakc0de or @Jasstkn can review this pr please ?

2021-07-17 05:07 UTC, Jasstkn requested changes
Hi! I've asked a couple of questions.

2021-07-17 05:07 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/README.md
> +| portal.frontend.rollingUpdate.enabled | bool | `false` |  |
why default is false? 

It's common to allow users to decide which strategy they want to use, default: RollingUpdate
```
{{- if .Values.frontend.updateStrategy }}
{{ toYaml .Values.frontend.updateStrategy | indent 2 }}
{{- end }}

  ## Strategy for deployment updates.
  ##
  ## Example:
  ##
  ##   strategy:
  ##     type: RollingUpdate
  ##     rollingUpdate:
  ##       maxSurge: 1
  ##       maxUnavailable: 25%
  strategy: {}
```

2021-07-17 05:07 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/templates/frontend-deployment.yaml
> +          {{- if .Values.portal.frontend.resources }}
you can replace it with:
```
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
```

2021-07-17 05:07 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +            {{- toYaml .Values.mongo.resources | nindent 12 }}
you can replace it with:
```
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
```

2021-07-17 05:29 UTC, HexalGJ commented on charts/litmus-2-0-0-beta/README.md
> +| portal.frontend.rollingUpdate.enabled | bool | `false` |  |
Hello, I set this default value to false so as not to impact the current behavior of a deployment already done.
I will make the modification in this way

2021-07-17 05:51 UTC, HexalGJ commented on charts/litmus-2-0-0-beta/templates/frontend-deployment.yaml
> +          {{- if .Values.portal.frontend.resources }}
Rajdas98 asked for [this change:](https://github.com/litmuschaos/litmus-helm/pull/142/files/94ae404ea82902c5011dd0577589cd43eacd7988)
The idea is to not generate 'empty' resources line in the manifest i think

2021-07-17 05:51 UTC, HexalGJ commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +            {{- toYaml .Values.mongo.resources | nindent 12 }}
same

2021-07-17 06:38 UTC, Jasstkn commented on charts/litmus-2-0-0-beta/templates/frontend-deployment.yaml
> +          {{- if .Values.portal.frontend.resources }}
@rajdas98 can you explain your point please? those conditions are ugly to read and I don't see if they are really applicable here.

2021-07-17 07:28 UTC, HexalGJ commented on charts/litmus-2-0-0-beta/README.md
> +| portal.frontend.rollingUpdate.enabled | bool | `false` |  |
I implemented it in the same way than resources ( with a value check).
according to @rajdas98 answer, I'll make needed edits for resources and strategy

2021-07-19 10:13 UTC, rajdas98 commented on charts/litmus-2-0-0-beta/templates/server-deployment.yaml
> +              port: graphql-srver
```suggestion
              port: graphql-server
```

2021-07-19 10:14 UTC, rajdas98 commented on charts/litmus-2-0-0-beta/templates/ingress.yaml
> +      - path: /
I think before 1.19, we need to add (.*)

2021-07-19 15:44 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/server-deployment.yaml
> +              port: graphql-srver
Hello Raj, thats the name of the port, i can edit it in the deployment template too if you want.

2021-07-19 16:07 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/ingress.yaml
> +      - path: /
I think its a Path Type configuration, not a kubernetes capabilities version ?
There is nothing about (.*) in the 1.18 documentation:
https://v1-18.docs.kubernetes.io/docs/concepts/services-networking/ingress/

We can leave it empty to set the default service to frontend.

I go the error thats why i fixed it.
Deployed with /(.*)
i cannot access https://my-domain-with-litmus.com/
i can access to https://my-domain-with-litmus.com/login

2021-07-22 20:30 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/ingress.yaml
> +      - path: /
I understood the issue.

https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus-2-0-0-beta/values.yaml#L30
Here the annotation is a commentary and there is nothing about the requirement of this.

This annotation is only valid for ingress nginx.
For traefik, the annotation should be :
`traefik.ingress.kubernetes.io/rewrite-target: $1
`
What about put those values as default ?
`
`nginx.ingress.kubernetes.io/rewrite-target: /$1
traefik.ingress.kubernetes.io/rewrite-target: $1
`

I remove the / cause it generate dirty http request on '/(.*)' like -> //statics/icons/...

2021-07-22 20:31 UTC, Vr00mm commented
Hello guys,

I push the readiness/liveness for graphql tomorow
with the asked changes.

See you later,
Best regards

2021-07-23 07:08 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/server-deployment.yaml
> +              port: graphql-srver
done

2021-07-23 07:09 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/ingress.yaml
> +      - path: /
Reverted, done

2021-07-23 07:09 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
> +            {{- toYaml .Values.mongo.resources | nindent 12 }}
done

2021-07-23 07:10 UTC, Vr00mm commented on charts/litmus-2-0-0-beta/templates/frontend-deployment.yaml
> +          {{- if .Values.portal.frontend.resources }}
done

2021-07-23 08:18 UTC, rajdas98 commented
Hi @Vr00mm There are some merge conflicts. Can you resolve it?

2021-07-23 09:18 UTC, Vr00mm commented
> Hi @Vr00mm There are some merge conflicts. Can you resolve it?

Hello @rajdas98 it should be OK for merge conflicts.

2021-07-23 13:10 UTC, Vr00mm commented
Ready to merge for me

2021-07-24 05:38 UTC, Jasstkn approved these changes
LGTM

2021-07-24 05:38 UTC, merged

2021-07-24 11:55 UTC, Vr00mm commented
Thanx for the merge