Feature/frontend svc annotations
litmuschaos/litmus-helm pull request #191
Opened 2022-01-07 17:26 UTC by lamc

@rajdas98 
@ispeakc0de
@Jasstkn 

#### What this PR does / why we need it:
Adds capability to add service annotations for litmusportal-frontend such as load balancer resource tags or type when installing LitmusChaos with LoadBalancer (as shown below)
```
service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags
service.beta.kubernetes.io/aws-load-balancer-type
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - NA

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-01-07 19:20 UTC, Jasstkn approved these changes
Hi. Thank you for your contribution! 
LGTM 🎉

2022-01-17 14:41 UTC, Jasstkn commented
@lamc hi. could you update from main branch?

2022-01-18 17:37 UTC, lamc commented
@Jasstkn I pulled from master, how would you like for me to proceed re the conflicts that came from pulling master branch? additionally, I see that my commits are signed off -- any suggestions?

2022-01-18 18:21 UTC, Jasstkn commented
> @Jasstkn I pulled from master, how would you like for me to proceed re the conflicts that came from pulling master branch? additionally, I see that my commits are signed off -- any suggestions?

pick up from master

2022-01-18 18:45 UTC, lamc commented
@Jasstkn got it, I pulled latest from master and fixed conflicts

2022-01-18 18:47 UTC, Jasstkn commented
> Details

please, bump chart version & run helm-docs.

2022-01-18 19:00 UTC, lamc commented
> > Details
> 
> please, bump chart version & run helm-docs.

@Jasstkn done!

2022-01-18 19:03 UTC, Jasstkn commented
> > > Details
> > 
> > 
> > please, bump chart version & run helm-docs.
> 
> @Jasstkn done!

DCO doesn't pass :(

2022-01-18 20:01 UTC, lamc commented
@Jasstkn all checks have passed!! 🎉 Please review 🙏

2022-01-19 05:24 UTC, uditgaurav approved these changes

2022-01-19 05:32 UTC, gdsoumya requested changes

2022-01-19 05:32 UTC, gdsoumya commented on charts/litmus/README.md
> +| minikube | bool | `false` |  |
This is not needed, was removed in master

2022-01-19 05:32 UTC, gdsoumya commented on charts/litmus/values.yaml
> +minikube: false
This is not needed, was removed in master

2022-01-19 15:35 UTC, gdsoumya approved these changes

2022-01-19 15:41 UTC, merged

2022-01-19 15:44 UTC, lamc commented
Thank you @Jasstkn @gdsoumya @uditgaurav for reviewing and responding so quickly! it was a pleasure working with ya'll 😄

2022-01-19 15:45 UTC, Jasstkn commented
> Thank you @Jasstkn @gdsoumya @uditgaurav for reviewing and responding so quickly! it was a pleasure working with ya'll 😄

Can't wait for your next contribution! You did well =)

2022-01-19 16:00 UTC, gdsoumya commented
> Thank you @Jasstkn @gdsoumya @uditgaurav for reviewing and responding so quickly! it was a pleasure working with ya'll smile

Thanks for the contribution! Looking forward to more!