ADD litmus-agent helm-chart
litmuschaos/litmus-helm pull request #200
Opened 2022-01-27 10:54 UTC by Vr00mm

Signed-off-by: Rémi ZIOLKOWSKI <remi.ziolkowski-ext@pole-emploi.fr>

#### What this PR does / why we need it:
This PR add an helm-chart for litmus-agent

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [] Chart Version bumped
- [X] Variables are documented in the README.md

2022-01-27 10:59 UTC, ksatchit commented
@Vr00mm thanks for adding this! Such images typically go into https://github.com/litmuschaos/test-tools. You could add a dedicated folder for the source! 

(I know the name 'test-tools' ins't entirely appropriate - we can discuss the name :-) )

2022-01-27 14:09 UTC, Vr00mm commented
Hello @ksatchit,
Thanx for details.
I created the pull request here -> https://github.com/litmuschaos/test-tools/pull/208

2022-02-11 04:56 UTC, gdsoumya requested changes

2022-02-11 04:56 UTC, gdsoumya commented on charts/litmus-agent/charts/subscriber/templates/hpa.yaml
> +{{- if .Values.autoscaling.enabled }}
We cannot scale the subscriber currently, there are limitations and edge cases that will break the portal on scaling subscriber.

2022-02-11 04:56 UTC, gdsoumya commented on charts/litmus-agent/charts/workflow-controller/templates/deployment.yaml
> +            -  litmuschaos/argoexec:v2.11.0
Possibly want this to be a variable

2022-02-11 04:56 UTC, gdsoumya commented on charts/litmus-agent/charts/workflow-controller/templates/deployment.yaml
> +            -  k8sapi
for the matter these are also configurable so best to kee the args as variable input and have default values.

2022-02-11 09:56 UTC, Vr00mm commented on charts/litmus-agent/charts/workflow-controller/templates/deployment.yaml
> +            -  litmuschaos/argoexec:v2.11.0
Done

2022-02-11 09:56 UTC, Vr00mm commented on charts/litmus-agent/charts/workflow-controller/templates/deployment.yaml
> +            -  k8sapi
Done

2022-02-11 09:58 UTC, gdsoumya approved these changes

2022-02-16 07:32 UTC, rajdas98 commented on charts/litmus-agent/templates/hook-pre-install-job.yaml
> +        image: "vr00mm/litmus-agent-registrer:0.6.0"
@Vr00mm We need to change the image registry

2022-08-25 15:12 UTC, closed without merging