support ingress class definition in spec
litmuschaos/litmus-helm pull request #214
Opened 2022-03-15 16:01 UTC by stoehdoi

Signed-off-by: stoehdoi <domi.stoehr@googlemail.com>

#### What this PR does / why we need it:
Ingress class should be defined in the spec rather than in the annotations: https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource 

#### Special notes for your reviewer:
For some ingress controller implementations this could be a breaking change. For example, the admission controller of nginx IC does not allow specifying the ingress class in both directives, annotations and spec. Hence, making the `.spec.ingressClassName` conditional. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

cc: @rajdas98 @ispeakc0de @Jasstkn

2022-03-15 20:29 UTC, Jasstkn commented on charts/litmus/templates/ingress.yaml
> +  {{- if .Values.ingress.ingressClassName }}
maybe it's better rely on the kubernetes version instead?

2022-03-16 07:52 UTC, stoehdoi commented on charts/litmus/templates/ingress.yaml
> +  {{- if .Values.ingress.ingressClassName }}
The Kubernetes version defines which api version of ingress resources are supported. However, it is the ingress controller version/implementation that actually handles these resources. Hence, the K8s version is no guarantee for it to work with the ingress class name in the spec. 

That's why I thought we give the choice to the users as they should know best which option to use. It would also be backwards compatible that way as we default `.ingress.ingressClassName` to empty string. If users don't change their values.yaml file but upgrade to a later chart version they won't face any issues.

2022-03-16 08:04 UTC, gdsoumya commented
@stoehdoi you need run helm docs to update the docs properly ref: https://github.com/norwoodj/helm-docs

2022-03-16 16:12 UTC, stoehdoi commented
@gdsoumya done

2022-03-18 07:57 UTC, stoehdoi commented on charts/litmus/templates/ingress.yaml
> +  {{- if .Values.ingress.ingressClassName }}
What do you think @Jasstkn

2022-03-21 22:28 UTC, Jasstkn commented on charts/litmus/templates/ingress.yaml
> +  {{- if .Values.ingress.ingressClassName }}
I still think that API version verification can be a good think but for the first iteration I don't mind your approach.

fyi: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/ingress.yaml

2022-03-21 22:28 UTC, Jasstkn approved these changes

2022-03-21 22:38 UTC, Jasstkn commented
@stoehdoi created a corresponded PR: https://github.com/litmuschaos/litmus-helm/pull/216 to update helm-docs.

2022-03-22 03:14 UTC, gdsoumya commented
@Jasstkn we can merge the helm docs PR first and update this PR before merging?

2022-03-22 04:05 UTC, gdsoumya commented
@stoehdoi can you update the docs, we have upgraded helm-docs

2022-03-23 11:56 UTC, gdsoumya approved these changes

2022-03-25 14:58 UTC, Jasstkn requested changes
@stoehdoi hi! could you please sign your commit?
https://github.com/litmuschaos/litmus-helm/pull/214/checks?check_run_id=5659424787

2022-03-26 16:02 UTC, rajdas98 commented
@Jasstkn. I passed the DCO manually. Merging this PR

2022-03-26 16:04 UTC, merged