Fixed OpenShift route: Service reference and service type ClusterIP
litmuschaos/litmus-helm pull request #217
Opened 2022-03-25 11:39 UTC by radudd

Fixed OpenShift route:
- the service reference for OpenShift route didn't include the RELEASE NAME in the naming
- the service type shall be clusterIP when using OpenShift Route

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2022-03-25 14:30 UTC, Jasstkn approved these changes

2022-04-10 13:26 UTC, Jasstkn requested changes
@radudd hi. could you please bump chart version and run helm-docs to update README?

2022-04-10 19:16 UTC, Jasstkn approved these changes
@rajdas98 could you take a look please?

2022-04-11 15:37 UTC, rajdas98 approved these changes

2022-04-13 04:23 UTC, merged