Release(2.8.0): Adds manifest for litmus core 2.8.0
litmuschaos/litmus-helm pull request #224
Opened 2022-04-17 07:23 UTC by uditgaurav

Signed-off-by: udit <udit@chaosnative.com>

#### What this PR does / why we need it:

-  Adds manifest for litmus core 2.8.0

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2022-04-18 09:41 UTC, Jasstkn requested changes
@uditgaurav hi. please, pay attention to lint & docs update jobs. 
Don't forget to use the latest version of helm-docs.

2022-04-26 09:53 UTC, avaakash approved these changes

2022-04-26 09:54 UTC, Jonsy13 approved these changes

2022-04-26 10:21 UTC, Jasstkn approved these changes

2022-04-26 10:21 UTC, merged