Bypass front nginx by forwarding requests directly from ingress to api and ws
litmuschaos/litmus-helm pull request #228
Opened 2022-05-04 07:41 UTC by RobinSegura

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
-    adding possibility to shunt front to directly pass requests from ingress to api
-    adding possibility to shunt front to directly pass requests from ingress to ws
-    adding possibility to shunt front to directly pass requests from ingress to auth

We need it to fasten calls to our services

#### Special notes for your reviewer:
replacement for https://github.com/litmuschaos/litmus-helm/pull/226 which was made on the wrong branch

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-05-04 07:45 UTC, RobinSegura commented
Thanks @Jasstkn for [your advice](https://github.com/litmuschaos/litmus-helm/pull/226#issuecomment-1115238770), i'm not familiar with circle ci

2022-05-05 08:45 UTC, Jasstkn commented
> Thanks @Jasstkn for [your advice](https://github.com/litmuschaos/litmus-helm/pull/226#issuecomment-1115238770), i'm not familiar with circle ci

Hey. Did you check failed buillds?

2022-05-05 12:48 UTC, RobinSegura commented
> > Thanks @Jasstkn for [your advice](https://github.com/litmuschaos/litmus-helm/pull/226#issuecomment-1115238770), i'm not familiar with circle ci
> 
> Hey. Did you check failed builds? Note: if you do some changes in charts' readme files you need to bump charts' version.

Hi :)
Yep but i didn't understood that i needed to bump every chart version, but only the modified one 
that should be fixed, Thanks 

however i'm still having this 'Docs are stale. Needs to be updated. Use helm-docs' issue on check-docs-update job
I'll have a look at it tonight :)

2022-05-10 13:54 UTC, RobinSegura commented
all fixed ! :+1:  
Good to go ! thanks for your help  @Jasstkn

2022-05-10 14:15 UTC, gdsoumya requested changes
Can you run this helm chart and verify it works, because the current config for auth endpoint should've failed

2022-05-10 14:15 UTC, gdsoumya commented on charts/litmus/templates/ingress.yaml
> +              number: 9002
should be 9003

2022-05-10 14:15 UTC, gdsoumya commented on charts/litmus/templates/ingress.yaml
> +            name: {{ $fullName }}-server-service
should be auth-server-service

2022-05-10 14:15 UTC, gdsoumya commented on charts/litmus/templates/ingress.yaml
> +          serviceName: {{ $fullName }}-server-service
should be auth-server-service

2022-05-12 08:18 UTC, RobinSegura commented on charts/litmus/templates/ingress.yaml
> +          serviceName: {{ $fullName }}-server-service
fixed in commit 52653744148035e127592b86a20407cbb6d324da

2022-05-12 08:18 UTC, RobinSegura commented on charts/litmus/templates/ingress.yaml
> +            name: {{ $fullName }}-server-service
commit 52653744148035e127592b86a20407cbb6d324da

2022-05-12 08:18 UTC, RobinSegura commented on charts/litmus/templates/ingress.yaml
> +              number: 9002
fixed in commit 52653744148035e127592b86a20407cbb6d324da

2022-05-12 08:19 UTC, Jasstkn commented
@RobinSegura 
>  litmus => (version: "2.8.2", path: "charts/litmus") > Chart version not ok. Needs a version bump!
Please, bump chart version & run helm-docs.

2022-05-15 15:37 UTC, Jasstkn commented
@RobinSegura hi. did you close PR?

2022-05-16 07:35 UTC, RobinSegura commented
> @RobinSegura hi. did you close PR?

Nop but my gh forked project has been removed. Had to fork it again and push a new bypass-front branch

2022-05-16 07:36 UTC, Jasstkn commented
> > @RobinSegura hi. did you close PR?
> 
> 
> 
> Nop but my gh forked project has been removed. Had to fork it again and push a new bypass-front branch 

Ah, I see. That's weird but feel free to open PR whenever it's ready :)

2022-05-16 08:00 UTC, closed without merging