feat: add mongo as external chart
litmuschaos/litmus-helm pull request #235
Opened 2022-06-08 14:23 UTC by itninja-hue

#### What this PR does / why we need it:
 Integrate bitnami/mongoDB as external chart
 Add the possibility to reference existing secrets
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #82

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-06-08 15:01 UTC, aslafy-z reviewed
See the comments above

2022-06-08 15:01 UTC, aslafy-z commented on charts/litmus/values.yaml
> +  DBUSER: ""
These are not used anymore

2022-06-08 15:01 UTC, aslafy-z commented on charts/litmus/values.yaml
> +  #https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
```suggestion

# -- Configure the Bitnami MongoDB subchart
# see values at https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
mongodb:
```

2022-06-08 15:02 UTC, aslafy-z commented
Shoudn't you delete the mongodb TGZ chart ?

2022-06-16 09:53 UTC, Jasstkn requested changes
@josephvano hi! thank you for your contribution!

To start review process, please, update your branch from the master and reply to the feedback from @aslafy-z .

2022-06-16 12:54 UTC, itninja-hue commented on charts/litmus/values.yaml
> +  DBUSER: ""
these are still used in case of specifying an external DB

2022-06-16 13:01 UTC, Jasstkn requested changes
Hey. Thanks for updating your branch. Could you check failed pipelines?

2022-06-17 08:24 UTC, aslafy-z commented on .circleci/ct.yaml
> +  - mongodb=https://charts.bitnami.com/bitnami
```suggestion
  - bitnami=https://charts.bitnami.com/bitnami
```

2022-06-17 08:25 UTC, aslafy-z commented on charts/litmus/values.yaml
> +  DBUSER: ""
```suggestion
  # -- leave empty if uses Mongo DB deployed by this chart
  DB_PASSWORD: ""
  DB_USER: ""
```

make these variables naming coherent

2022-06-20 18:15 UTC, aslafy-z approved these changes

2022-06-24 15:08 UTC, gdsoumya commented on charts/litmus/Chart.yaml
> +apiVersion: v2
not sure if we need to update this @Jasstkn do we usually update this version?

2022-06-24 15:10 UTC, gdsoumya commented on charts/litmus/README.md
> +| portal.server.service.type | string | `"ClusterIP"` |  |
same here

2022-06-24 15:15 UTC, gdsoumya commented on charts/litmus/values.yaml
> +  DB_PORT: ""
the default values should be left in incase user doesn't use existing secret?

2022-06-24 15:22 UTC, gdsoumya commented on charts/litmus/values.yaml
> +    rootPassword: "superhardpassword"
if the password is here we should remove the db user and password values from admin config and just put the auth details directly here and use them in the secret. Don't see any reason to have separate configuration values for mongo

2022-06-25 09:56 UTC, Jasstkn commented on charts/litmus/Chart.yaml
> +apiVersion: v2
Version should be update only if we remove support for helm v2.

2022-06-25 09:58 UTC, Jasstkn commented on charts/litmus/README.md
> +| portal.frontend.service.type | string | `"ClusterIP"` |  |
@gdsoumya I disagree. Seems like ClusterIP is a default and more secure way to access application without exposing it.

2022-06-25 09:58 UTC, Jasstkn commented on charts/litmus/README.md
> +| portal.server.service.type | string | `"ClusterIP"` |  |
https://github.com/litmuschaos/litmus-helm/pull/235#discussion_r906663241

2022-06-25 13:47 UTC, gdsoumya commented on charts/litmus/README.md
> +| portal.frontend.service.type | string | `"ClusterIP"` |  |
I said unwanted because our defaults were NodePort, the logic behind that was people usually will run this locally in their local minikube/k3s clusters first where it is fine and easier to use node port to access the services. If a user is running in prod they will surely convert to ClusterIp and use Ingress/ LB. It's fine if we agree to move to ClusterIp defaults.

2022-06-25 13:50 UTC, Jasstkn commented on charts/litmus/README.md
> +| portal.frontend.service.type | string | `"ClusterIP"` |  |
I guess regarding a local setup we can reflect these values in docs, e.g.:
- if you install locally, pass --set portal.frontend.service.type=NodePort to access application via minikube(other) IP address and port.

2022-06-25 13:54 UTC, gdsoumya commented on charts/litmus/README.md
> +| portal.frontend.service.type | string | `"ClusterIP"` |  |
@Jonsy13 probably best to mention this in our docs from now, in case the doc expects the default to be nodeport

2022-06-27 06:40 UTC, imrajdas requested changes
As discussed with @ksatchit, We need to add an env var to get the flavor of mongo that users want. 

Option will be- {normal mongosts, bitnami mongo & percona mongo}

@itninja-hue Can we accommodate this with your PR?

2022-06-28 08:31 UTC, itninja-hue commented on charts/litmus/Chart.yaml
> +apiVersion: v2
The changes of the apiVersion was done to be able to use the field *dependencies*  in Chart.yaml defining chart dependencies.

2022-06-28 08:35 UTC, itninja-hue commented on charts/litmus/values.yaml
> +    rootPassword: "superhardpassword"
DBUSER, DBPASSWORD, DB_SERVER, DB_PORT fields from adminConfig are kept to be used in case of using an external database (not deployed by this chart) 

https://github.com/Carrefour-Group/litmus-helm/blob/feat/add_mongo_external_chart/charts/litmus/templates/controlplane-secrets.yaml#L11 
https://github.com/Carrefour-Group/litmus-helm/blob/feat/add_mongo_external_chart/charts/litmus/templates/controlplane-configs.yaml#L12 
https://github.com/Carrefour-Group/litmus-helm/blob/feat/add_mongo_external_chart/charts/litmus/values.yaml#L20

2022-06-28 08:41 UTC, itninja-hue commented
@imrajdas   Since this chart in this PR supports external Database integration adding other mongo dependencies will take the PR out of context of the issue it resolves maybe it would be best to open other issues for adding other mongodb flavors to be able to scope discussions , what do you think ?

2022-06-28 08:42 UTC, itninja-hue commented on charts/litmus/values.yaml
> +  DB_PORT: ""
https://github.com/litmuschaos/litmus-helm/pull/235#discussion_r908199793

2022-07-05 04:06 UTC, imrajdas commented
> @imrajdas Since this chart in this PR supports external Database integration adding other mongo dependencies will take the PR out of context of the issue it resolves maybe it would be best to open other issues for adding other mongodb flavors to be able to scope discussions , what do you think ?

Yeah sure, You can add the bitnami mongo only, but we need some kind of env var to switch b/w different mongos.

2022-07-11 15:18 UTC, itninja-hue commented
ping @Jasstkn  @gdsoumya  can you resolve / answer your comments/change request i would very much appreciate it

2022-07-11 15:20 UTC, Jasstkn commented
> ping @Jasstkn @gdsoumya can you resolve / answer your comments/change request i would very much appreciate it this PR is 1 month old already drifted from master AGAIN

Hi. I personally believe that having several databases as supported introduces unwanted complication and overload. Bitnami should be enough as soon as we have an option to disable its deployment and configure another (already deployed) instance.

2022-07-18 13:19 UTC, Jasstkn commented
> > ping @Jasstkn @gdsoumya can you resolve / answer your comments/change request i would very much appreciate it this PR is 1 month old already drifted from master AGAIN
> 
> Hi. I personally believe that having several databases as supported introduces unwanted complication and overload. Bitnami should be enough as soon as we have an option to disable its deployment and configure another (already deployed) instance.

@gdsoumya what do you think?

2022-07-29 17:16 UTC, aslafy-z commented
@gdsoumya Quick ping as we'd love this to be shipped!

2022-08-03 04:03 UTC, gdsoumya approved these changes
Apologize for the late reply, I am good with this. Though will wait for @imrajdas to confirm if he's satisfied with the db switching aspect, before merging.

2022-08-03 06:58 UTC, Jasstkn commented
> @gdsoumya @Jasstkn Quick ping as we'd love this to be shipped!

hi. could you resolve merge conflicts?

2022-08-03 22:13 UTC, itninja-hue commented
> > @gdsoumya @Jasstkn Quick ping as we'd love this to be shipped!
> 
> hi. could you resolve merge conflicts?

Done

2022-08-04 12:53 UTC, itninja-hue commented
ping @imrajdas  and @Jasstkn  can you please close the change requests as it was resolved

2022-08-04 13:28 UTC, Jasstkn commented
> ping @imrajdas and @Jasstkn can you please close the change requests as it was resolved

Hey. I'll review it later today.

2022-08-04 19:57 UTC, Jasstkn requested changes
Hi. 

I've made few comments. Also I was trying to install chart with your changes locally and mongo coudn't start. Current version is installed without no troubles. 

I guess the issue is in the mongodb's configuration. If you don't have any suggestions, I'll investigate next week.

2022-08-04 19:57 UTC, Jasstkn commented on charts/litmus/values.yaml
> +  replicaCount: 3
should be one as it was in the initial configuration.
main idea is to provide minimal setup for litmus to be up and running after chart's installation. So, we don't need 3 replicas of mongodb. Also, please, disable arbiter installment.

2022-08-04 19:57 UTC, Jasstkn commented on charts/litmus/values.yaml
> +    rootPassword: "superhardpassword"
please, add a note here about changing a password and that it can be done via e.g. `existingSecret`

2022-08-05 09:01 UTC, itninja-hue commented
> Hi.
> 
> I've made few comments. Also I was trying to install chart with your changes locally and mongo coudn't start. Current version is installed without no troubles.
> 
> I guess the issue is in the mongodb's configuration. If you don't have any suggestions, I'll investigate next week.

can you be more explicit ? what state does the mongoDB pods get stuck in ? 
i see no problem with the chart in my end on multiple environments

2022-08-05 09:08 UTC, Jasstkn commented
> > Hi.
> > I've made few comments. Also I was trying to install chart with your changes locally and mongo coudn't start. Current version is installed without no troubles.
> > I guess the issue is in the mongodb's configuration. If you don't have any suggestions, I'll investigate next week.
> 
> can you be more explicit ? what state does the mongoDB pods get stuck in ? i see no problem with the chart in my end on multiple environments

i've tried to deploy it to kind cluster. It stuck in the env loading line and fails because of health checks. It can be my local issue or performance but as I mentioned no issues with current chart.

2022-08-05 13:58 UTC, aslafy-z approved these changes
Tested, it works well on my side. LGTM! :rocket:

2022-08-05 18:22 UTC, imrajdas approved these changes

2022-08-05 18:22 UTC, merged

2022-08-05 18:22 UTC, imrajdas commented
Thanks for this PR