feat: add existingSecret value to override secret with ext secrets
litmuschaos/litmus-helm pull request #236
Opened 2022-06-08 20:55 UTC by josephvano

* add helper methods to create secret
* add helper method to get secre name
* update refs for secret to use helper method

Signed-off-by: Joseph Vano <joseph.vano@gmail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-06-16 09:53 UTC, Jasstkn requested changes
@josephvano hi! thank you for your contribution!

To start review process, please, update your branch from the master and resolve any conflicts on the way.

2022-06-16 12:01 UTC, Jasstkn commented
> Hi @Jasstkn I've rebased from master. Thanks

I see you have a failed job about updating docs. Did you check our contributing guide?
https://github.com/litmuschaos/litmus-helm/blob/master/CONTRIBUTING.md#how-to-contribute

2022-06-18 12:09 UTC, josephvano commented
Hi @Jasstkn I've updated the helm-docs and rebased again.

I'm not sure why there is an error with the `lint-charts` check with validation of maintainers.

2022-06-18 12:20 UTC, Jasstkn commented
> Hi @Jasstkn I've updated the helm-docs and rebased again.
> 
> I'm not sure why there is an error with the `lint-charts` check with validation of maintainers.

Thanks. I'm fixing the issue right now. :)

2022-06-20 20:16 UTC, Jasstkn approved these changes
Hi @josephvano! Again thank you for your contribution. LGTM :)

2022-06-20 20:18 UTC, Jasstkn commented
@ispeakc0de @imrajdas Hi folks. Please, review this PR. :)

2022-06-25 10:08 UTC, Jasstkn commented
> @ispeakc0de @imrajdas Hi folks. Please, review this PR. :)

@ispeakc0de @imrajdas ping

2022-07-04 21:15 UTC, agcorrea commented
+1

2022-07-11 15:32 UTC, josephvano commented
Rebased

ready for review again @ispeakc0de @imrajdas

2022-07-11 16:17 UTC, imrajdas approved these changes

2022-07-12 10:36 UTC, Jonsy13 requested changes

2022-07-12 10:36 UTC, Jonsy13 commented on charts/litmus/Chart.yaml
> +version: 2.11.0
Can we please change it to **`2.10.3`**

2022-07-12 10:36 UTC, Jonsy13 commented on charts/litmus/README.md
> +![Version: 2.11.0](https://img.shields.io/badge/Version-2.11.0-informational?style=flat-square) ![AppVersion: 2.10.0](https://img.shields.io/badge/AppVersion-2.10.0-informational?style=flat-square)
Can we please change it to **`2.10.3`**

2022-07-12 11:19 UTC, Jonsy13 approved these changes

2022-07-12 11:54 UTC, merged