Feat/add hpa
litmuschaos/litmus-helm pull request #265
Opened 2022-08-09 14:33 UTC by itninja-hue

#### What this PR does / why we need it:
Adds HPA for authsever , frontend and server deployment.
enable autoscaling for load peaks.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-08-09 14:47 UTC, Jasstkn commented
@itninja-hue hi. please, take a look into failed jobs.

2022-08-09 14:54 UTC, Jasstkn approved these changes
LGTM

2022-08-09 15:32 UTC, aslafy-z approved these changes
LGTM

2022-08-09 15:32 UTC, aslafy-z commented on charts/litmus/Chart.yaml
> +version: 2.12.1
@Jasstkn should the minor be bumped in here? Or patch is ok?

2022-08-09 15:42 UTC, Jasstkn commented
> LGTM 

Patch is fine by me.

2022-08-09 18:42 UTC, gdsoumya approved these changes

2022-08-09 18:42 UTC, gdsoumya commented on charts/litmus/README.md
> +| portal.server.autoscaling.targetMemoryUtilizationPercentage | int | `50` |  |
all graphql config needs to be under `graphqlServer` for consistency, it seems other existing configs for gql server is also not grouped together properly, we should surely clean this up sometime @Jasstkn @imrajdas @Jonsy13

2022-08-09 18:48 UTC, Jasstkn commented on charts/litmus/README.md
> +| portal.server.autoscaling.targetMemoryUtilizationPercentage | int | `50` |  |
Yes, nice catch tho. I'll create an issue to figure out a better structure for our components.

2022-08-10 05:47 UTC, imrajdas requested changes

2022-08-10 05:47 UTC, imrajdas commented on charts/litmus/templates/server-hpa.yaml
> +{{- if .Values.portal.server.autoscaling.enabled -}}
gql server can't be horizontal scale. So, we can remove this spec

2022-08-10 05:47 UTC, imrajdas commented on charts/litmus/values.yaml
> +      maxReplicas: 3
same:
gql server can't be horizontal scale. So, we can remove this spec

2022-08-10 07:39 UTC, itninja-hue commented on charts/litmus/templates/server-hpa.yaml
> +{{- if .Values.portal.server.autoscaling.enabled -}}
how come ?  
the ability to change the number of replicas is present on stable (master) 
 https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/values.yaml#L144 
 https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/server-deployment.yaml#L13 
 
 Please can you give more details  :pray:

2022-09-12 17:09 UTC, aslafy-z commented
@itninja-hue Please rebase and bump the Chart version.

2022-09-14 16:46 UTC, itninja-hue commented
@Jasstkn  @imrajdas  @gdsoumya  ping i see the pipe failing on azure due to  
```Error
/usr/local/bin/kind: line 1: Error: command not foun
```

2022-09-20 16:17 UTC, Jasstkn commented
@imrajdas hey. can you give more detailed feedback if this change is valid or not?

2022-10-04 14:33 UTC, Jonsy13 commented
Added @Adarshkumar14 for review

2022-10-04 14:33 UTC, Jonsy13 commented
Also resolve conflicts in this PR.

2022-10-05 13:00 UTC, Adarshkumar14 approved these changes
LGTM

2022-10-09 09:17 UTC, Jasstkn approved these changes

2022-10-09 09:19 UTC, Jasstkn requested changes
Hey. Everything looks great - just a small note, could you bump only patch version of chart? we have an agreement to follow the litmus version here and all changes should be done via patch version.

I'll add a note about it in contribution guide. Thanks in advance!

2022-10-10 08:36 UTC, merged

2022-10-10 08:36 UTC, Jasstkn commented
@itninja-hue thanks again for your contribution!