Allow users to set custom mongodb connection URIs
litmuschaos/litmus-helm pull request #272
Opened 2022-08-25 01:56 UTC by dmyerscough

#### What this PR does / why we need it:

This PR allows more flexibility in configuring an external MongoDB instance. For example, MongoDB can be configured with a seed list via SRV records e.g. `mongodb+srv://cluster0.example.mongodb.net`. 

There is an initalization container that waits for MongoDB to become available. However, we should allow this initialization container to be enabled/disabled. This is handy when using an external MongoDB instance that we know is running.

I tested this PR with the MongoDB free hosted tier. When configuring the external MongoDB instance, I set `mongodb.enabled` to false and set `portal.server.waitForMongodb.enabled` to false.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-09-20 19:51 UTC, Jasstkn requested changes

2022-09-20 19:51 UTC, Jasstkn commented on charts/litmus/templates/auth-server-deployment.yaml
> +      {{- if and (.Values.portal.server.waitForMongodb.enabled) (.Values.mongodb.enabled) }}
why and? I think it's enough to check first variable.

2022-09-20 19:51 UTC, Jasstkn commented on charts/litmus/templates/server-deployment.yaml
> +      {{- if and (.Values.portal.server.waitForMongodb.enabled) (.Values.mongodb.enabled) }}
same here

2022-09-20 20:40 UTC, dmyerscough commented on charts/litmus/Chart.yaml
> -version: 2.13.0
You might want to update the README.md file as I didn't see any reference to the [versioning](https://github.com/litmuschaos/litmus-helm/blob/master/CONTRIBUTING.md#versioning)

I can raise the patch level.

2022-09-20 20:47 UTC, dmyerscough commented on charts/litmus/templates/auth-server-deployment.yaml
> +      {{- if and (.Values.portal.server.waitForMongodb.enabled) (.Values.mongodb.enabled) }}
I can see this could be a little over-excessive, removed and just kept `waitForMongodb`

2022-09-20 20:47 UTC, dmyerscough commented on charts/litmus/templates/server-deployment.yaml
> +      {{- if and (.Values.portal.server.waitForMongodb.enabled) (.Values.mongodb.enabled) }}
Addressed above.

2022-09-21 09:03 UTC, Jasstkn commented on charts/litmus/Chart.yaml
> -version: 2.13.0
That's right, we didn't make an agreement so far but I'll create an issue to track this. 
Fyi @ksatchit

2022-09-21 09:05 UTC, Jasstkn requested changes
Code changes look fine to me. 
Regarding checks - could you login to circle ci and check if you see any errors? 
Also it looks like you didn't sign your commit.

2022-09-22 03:06 UTC, dmyerscough commented
@Jasstkn Just resigned the commit and CI looks good.

2022-09-22 07:21 UTC, Jasstkn approved these changes
LGTM.

2022-09-22 07:22 UTC, Jasstkn commented
@imrajdas @ispeakc0de @Jonsy13 hello. could you review this PR?

2022-10-04 05:29 UTC, dmyerscough commented
@Jasstkn What's the PR process? This PR has been open for a while now and there is zero traction, should I consider this dead and just work from a forked version?

2022-10-04 14:35 UTC, ksatchit commented
@dmyerscough - apologies on the delayed reviews. Thanks @Jasstkn for helping with increased time on this repo
 
The team should be able to get back to normal review cycles very soon. 

Meanwhile, like the idea of providing the flag to enable/disable waitForMongo init container.

2022-10-04 14:36 UTC, Jonsy13 approved these changes

2022-10-04 14:46 UTC, aslafy-z commented on charts/litmus/templates/_helpers.tpl
> +{{- if .Values.adminConfig.DB_SERVER }}
In #243, I add another value called DB_URL. I think the same should be implemented here to avoid misunderstanding and double possible format for a same variable. It looks clearer to me. Let me know it this makes sense to you. 
Also, I think it would be great to add a note to the value file / readme.

2024-05-13 11:58 UTC, uditgaurav commented
Hi @dmyerscough , We already have this capability now. Please refer the [README.md](https://github.com/litmuschaos/litmus-helm/tree/master/charts/litmus#values) to know more. Feel free to reopen in case you have any thoughts.

Thanks

2024-05-13 11:58 UTC, closed without merging