Allow customLabels for the exporter deployment
litmuschaos/litmus-helm pull request #280
Opened 2022-10-05 04:59 UTC by dmyerscough

#### What this PR does / why we need it:

This PR is to allow custom labels to be set on the `exporter` deployment. The reason you might want to add custom labels on the exporter vs exporter/operator is to instruct a scraper to scrape the metrics endpoint. The current custom labels set the label on both the operator and exporter deployment.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-10-06 04:57 UTC, dmyerscough commented
Does this PR look reasonable to you?

cc @Jasstkn

2022-10-08 13:31 UTC, gdsoumya requested changes

2022-10-08 13:31 UTC, gdsoumya commented on charts/litmus-core/templates/_helpers.tpl
>  {{ toYaml .Values.customLabels }}
This one is a custom set of labels that's applied to all resources and not just the operator deployment. So maybe remove the deplyoment lable check.

2022-10-13 04:58 UTC, dmyerscough commented on charts/litmus-core/templates/_helpers.tpl
>  {{ toYaml .Values.customLabels }}
@gdsoumya just updated this.

2022-10-13 05:17 UTC, closed without merging

2022-10-13 05:17 UTC, dmyerscough commented
Ill open a new request to address this