Allow custom annotations to be set on the exporter deployment
litmuschaos/litmus-helm pull request #281
Opened 2022-10-13 05:31 UTC by dmyerscough

This PR allows you to set custom annotations on the exporter deployment. This allows users to add custom Prometheus/DataDog annotations so the metrics can be scraped.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-10-13 07:11 UTC, gdsoumya requested changes

2022-10-13 07:11 UTC, gdsoumya commented on charts/litmus-core/templates/exporter-deployment.yaml
> +        {{- end }}
seems like the indentation here isn't right, could be just github rendering it wrong but `annotations` should be in the same indentation as `labels`. Can you confirm the manifest is being rendered properly?

2022-10-13 11:52 UTC, Jasstkn requested changes
Hey. Could you run `helm-docs` locally to generate readme files and also there is a typo in the `exporter-deployment.yaml`

2022-10-13 11:52 UTC, Jasstkn commented on charts/litmus-core/templates/exporter-deployment.yaml
> +        {{- end }}
yes, it should be 2 more spaces to the right
```
        {{- if .Values.exporter.annotations }}
        annotations:
          {{- toYaml .Values.exporter.annotations | nindent 10 }}
        {{- end }}
```

2022-10-14 04:41 UTC, dmyerscough commented
Thank you @gdsoumya @Jasstkn for the review, just pushed new updates.

2022-10-14 04:47 UTC, gdsoumya approved these changes

2022-10-14 08:21 UTC, Jasstkn approved these changes

2022-10-14 08:21 UTC, merged