fix post-upgrade-hook imagePullSecretes
litmuschaos/litmus-helm pull request #290
Opened 2022-11-24 10:30 UTC by bingwei-hong-partior

Signed-off-by: bingwei-hong-partior <bingwei.hong@partior.com>

#### What this PR does / why we need it:
 This is to fix post-upgrade-hook.yaml missing imagePullSecrets tag when using private image registry that requires authentication.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #289 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] DCO signed

2022-11-24 10:32 UTC, gdsoumya approved these changes
Thanks for the fix! LGTM

2022-11-24 10:33 UTC, gdsoumya commented
Oh just noticed you forgot to bump the chart version and regenerate the docs. @bingwei-hong-partior can you bump the version and generate the docs

2022-11-24 10:42 UTC, Jasstkn requested changes

2022-11-24 10:42 UTC, Jasstkn commented on charts/litmus/templates/post-upgrade-hook.yaml
> +        {{ toYaml .Values.image.imagePullSecrets | indent 8 }}
It should be `nindent` here instead of indent.

2022-11-24 10:45 UTC, Jasstkn commented
@bingwei-hong-partior hello! thanks for your contribution. One of the jobs is failed, to fix this you need to run `helm-docs`. This step is mentioned in our [contribution guide](https://github.com/litmuschaos/litmus-helm/blob/master/CONTRIBUTING.md#how-to-contribute). 

Let me know if you have questions!

2022-11-24 10:56 UTC, bingwei-hong-partior commented on charts/litmus/templates/post-upgrade-hook.yaml
> +        {{ toYaml .Values.image.imagePullSecrets | indent 8 }}
OK, will change.

2022-11-24 11:04 UTC, bingwei-hong-partior commented
Hi, I've done the chart version bump, docs update and use nindent . anything else needed?

2022-11-24 11:17 UTC, bingwei-hong-partior commented
Sorry, first time contributing, appologise if I didn't get all process correctly

2022-11-24 11:17 UTC, Jasstkn commented
> Hi, I've done the chart version bump, docs update and use nindent . anything else needed?

nope, it fails for another chart.

2022-11-24 11:18 UTC, Jasstkn commented
> Sorry, first time contributing, appologise if I didn't get all process correctly

it's fine. let me check...

2022-11-24 11:19 UTC, Jasstkn commented on charts/litmus/README.md
> -----------------------------------------------
was the line delete automatically? it shouldn't

2022-11-24 11:23 UTC, bingwei-hong-partior commented on charts/litmus/README.md
> -----------------------------------------------
Hmm it was generated by helm-docs

2022-11-24 11:46 UTC, Jasstkn commented on charts/litmus/README.md
> -----------------------------------------------
I ran helm-docs from your branch and it reverts deletion of this line. I use 
```
helm-docs --version
helm-docs version 1.11.0
```

2022-11-25 02:05 UTC, bingwei-hong-partior commented on charts/litmus/README.md
> -----------------------------------------------
![image](https://user-images.githubusercontent.com/114902409/203885741-4b8e7e32-7ff9-423a-a5e7-b777b184ba08.png)
![image](https://user-images.githubusercontent.com/114902409/203885782-8f619423-78b4-4a50-94f0-a1352992846f.png)
OK, regenerated using version 1.11.0

2022-11-25 03:41 UTC, bingwei-hong-partior commented on charts/litmus/README.md
> -----------------------------------------------
Hi @Jasstkn , is everything good? anything else I need to change?

2022-11-25 03:44 UTC, gdsoumya commented on charts/litmus/README.md
> -----------------------------------------------
Everything seems to be passing, all good.

2022-11-25 08:00 UTC, Jasstkn approved these changes
@bingwei-hong-partior thank again for your contribution! It looks good to me!

2022-11-25 08:00 UTC, merged