Use Existing Secret in litmus-agent values.yaml
litmuschaos/litmus-helm pull request #313
Opened 2023-02-27 18:31 UTC by flockoftanks

#### What this PR does / why we need it:
The existing chart may force a user to put a password in source-control. This encourages bad security practices. This fix allows a user to specify a custom secret that can be used instead of the default template.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #311 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] DCO signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md

2023-02-28 08:37 UTC, Jasstkn commented
@flockoftanks Hi. Thanks for your PR. Please, take a look into our [Contributing guide](https://github.com/litmuschaos/litmus-helm/blob/master/CONTRIBUTING.md).

From what I can observe you need to do the following:
- generate readme documentation with helm-docs (I also left a comment about format)
- check if default configuration fails to install

2023-02-28 08:39 UTC, Jasstkn requested changes

2023-02-28 08:39 UTC, Jasstkn commented on charts/litmus-agent/values.yaml
> +existingHookSecret: ""
Use the following format:
```
# -- Name of existing secret to use for ..., ref. to templates/secret.yaml
```

2023-02-28 15:02 UTC, flockoftanks commented on charts/litmus-agent/values.yaml
> +existingHookSecret: ""
Thought of a new (cleaner) way of doing this. User can use the `litmus-agent-hook` secret name but disable the creation of that secret to defer to the user's custom secret. 

Let me know if you prefer the custom secret name version from before and I can put it back that way. 

I put more info in the comment in `values.yaml` and moved the `# --` comment to the bottom so the description in the docs would be more readable at a glance.

2023-02-28 15:03 UTC, Jasstkn commented on charts/litmus-agent/values.yaml
> +existingHookSecret: ""
the first implementation is more well known and can be found in many other community charts. Let's stick with it.

2023-02-28 15:33 UTC, flockoftanks commented
> @flockoftanks Hi. Thanks for your PR. Please, take a look into our [Contributing guide](https://github.com/litmuschaos/litmus-helm/blob/master/CONTRIBUTING.md).
> 
> From what I can observe you need to do the following:
> 
> * generate readme documentation with helm-docs (I also left a comment about format)
> * check if default configuration fails to install

Any idea what's causing the install to fail? I'm not familiar enough with litmus-agent, but I don't see any useful error messages in the log.

2023-02-28 19:10 UTC, Jasstkn commented
@ispeakc0de hi. can you help here? it gives the same error when I install chart with default values locally. 

```bash
k logs -f install-litmus-agent-8cmfr
invalid character '<' looking for beginning of value
```

2023-03-01 08:22 UTC, Jasstkn commented
> @ispeakc0de hi. can you help here? it gives the same error when I install chart with default values locally.
> 
> ```shell
> k logs -f install-litmus-agent-8cmfr
> invalid character '<' looking for beginning of value
> ```

I think I may have an idea - this chart shouldn't be deployed during our CI. I will fix within the next few days.

2023-03-01 19:18 UTC, Shashankreddy6 commented
> > @ispeakc0de hi. can you help here? it gives the same error when I install chart with default values locally.
> > ```shell
> > k logs -f install-litmus-agent-8cmfr
> > invalid character '<' looking for beginning of value
> > ```
> 
> I think I may have an idea - this chart shouldn't be deployed during our CI. I will fix within the next few days.

Is this with respect to the added parameter of external secret in litmus-agent?

2023-03-02 09:23 UTC, Jasstkn commented
> > > @ispeakc0de hi. can you help here? it gives the same error when I install chart with default values locally.
> > > ```shell
> > > k logs -f install-litmus-agent-8cmfr
> > > invalid character '<' looking for beginning of value
> > > ```
> > 
> > 
> > I think I may have an idea - this chart shouldn't be deployed during our CI. I will fix within the next few days.
> 
> Is this with respect to the added parameter of external secret in litmus-agent?

nope. it's just with default values. I think that the problem here is that this chart requires litmus to be installed. Therefore it's not suitable for independent tests. I'm going to exclude it.

2023-03-02 12:59 UTC, gdsoumya requested changes

2023-03-02 12:59 UTC, gdsoumya commented on charts/litmus-agent/values.yaml
> +# `{{ include "litmus-agent.fullname" . }}-hook`
I think this should be `{{ include "subscriber.fullname" . }}-hook` to match with the existing secret. the underlying values maybe same for now but it can change in future.

2023-03-02 15:25 UTC, flockoftanks commented on charts/litmus-agent/values.yaml
> +# `{{ include "litmus-agent.fullname" . }}-hook`
Changed to match secret file.

2023-03-03 14:18 UTC, flockoftanks commented
So, to clarify, am I waiting for something to change in the master branch that I will merge into this to fix the build? 

Thanks for your help so far everyone!

2023-03-10 13:20 UTC, Shashankreddy6 commented
Any update on this @Jasstkn @gdsoumya .

2023-03-10 13:38 UTC, Jasstkn commented
@flockoftanks @Shashankreddy6 hey! I submitted PR: https://github.com/litmuschaos/litmus-helm/pull/314, waiting for approval.

2023-03-12 07:44 UTC, Jasstkn commented
@flockoftanks I made a fix in the main branch. Please, squash your commits, sign it and we will be able to merge it. Thanks!

2023-04-21 17:10 UTC, flockoftanks commented
Hey, sorry. Been AWOL.  I'll get this merged up.

2023-04-21 17:22 UTC, flockoftanks commented
Not sure how to signoff on your commits that I synced to my branch. When I merged it said I didn't pass TCO checks because your most recent commits in my commit history weren't signed by me.

Following the directions in the "learn more" link and force pushing those signoffs, I think I got some of YOUR commits credit to me. Let me know if I need to change something.

2023-09-15 13:48 UTC, Calvinaud commented
Hello, I would to be interested by this PR (I can aslo work on it if needed). @flockoftanks Are you still working on this PR ?

2024-05-29 07:53 UTC, sambonbonne commented
@uditgaurav maybe two weeks is a short delay but it seems the work has stopped on this PR (I'm not saying this negatively, we all have our own life). Would you accept a new PR from someone else? I may have some time for this next week but I don't want to supersede @flockoftanks work if that's not OK.

2024-07-16 09:30 UTC, Jonsy13 commented
Hi @flockoftanks Closing this PR due to inactivity and also there is one PR merged by @sambonbonne for same changes.
Feel free to open this PR again if there are any further changes.

2024-07-16 09:30 UTC, closed without merging