Add security context for wait-for-mongodb
litmuschaos/litmus-helm pull request #332
Opened 2023-08-28 14:50 UTC by Calvinaud

- Add securityContext in values.yaml
- Using this securityContext in auth-server-deployment.yaml and server-deployment.yaml
- Bumping Chart version to 2.16.0 (I hesitate between bumping to 2.16.0 or 2.15.12 cause not sure if this change can be considered a bug fix)
- Regenerating docs with helm-docs

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #331

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2023-08-28 14:51 UTC, Calvinaud commented
I was not sure if this change needed to be considered as a bug fix (and bump to 2.15.11) or a added feature (and bump to 2.16.0). I can change if needed.

2023-08-29 07:32 UTC, Calvinaud commented
Didn't see the PR, https://github.com/litmuschaos/litmus-helm/pull/212. Should I close this one in favor of the previous one ?

2023-08-29 12:43 UTC, Jasstkn commented
Let me take a look. Will reply by EOD, thanks!

2023-08-29 19:34 UTC, Jasstkn requested changes

2023-08-29 19:34 UTC, Jasstkn commented on charts/litmus/Chart.yaml
> -version: 2.15.10
we bump only patch versions, more about this decision is [here](https://github.com/litmuschaos/litmus-helm/blob/master/CONTRIBUTING.md#versioning)

2023-08-29 19:34 UTC, Jasstkn commented on charts/litmus/values.yaml
> +      securityContext:
I would prefer to have the default as empty value and let user to define it. If you want, you can leave the suggested values commented.

2023-08-29 19:34 UTC, Jasstkn commented
> Let me take a look. Will reply by EOD, thanks!

Mentioned PR wasn't updated on requested, closed it in favor of yours. Please, let me know if you have any questions about the comments that I've left.

2023-08-30 07:20 UTC, Calvinaud commented on charts/litmus/values.yaml
> +      securityContext:
I would think to be put more security by default and let people remove it if needed. Updated the PR so securityContext is empty in default.

2023-08-30 07:22 UTC, Calvinaud commented on charts/litmus/Chart.yaml
> -version: 2.15.10
Switch to bumping to 2.15.11. And sorry for my last PR I bumped the minor on litmus-agent.

2023-08-30 09:45 UTC, Jasstkn approved these changes
LGTM 🚀 Thank you for your contribution!

@imrajdas @ispeakc0de can you take a look here?

2023-08-31 13:19 UTC, merged

2023-08-31 13:20 UTC, Jasstkn commented
@Calvinaud gonna be released in a few moments!