Add labels in openshift route resource
litmuschaos/litmus-helm pull request #337
Opened 2023-10-02 14:00 UTC by Calvinaud

- Add common and custom labels to the route resource
- Upgrade chart version to 2.15.12
- Regenerate doc with helm-docs

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #336

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2023-10-11 15:00 UTC, gdsoumya requested changes

2023-10-11 15:00 UTC, gdsoumya commented on charts/litmus/README.md
> +![Version: 3.0.1](https://img.shields.io/badge/Version-3.0.0-informational?style=flat-square) ![AppVersion: 3.0.0](https://img.shields.io/badge/AppVersion-3.0.0-informational?style=flat-square)
Should this be?

```suggestion
![Version: 3.0.1](https://img.shields.io/badge/Version-3.0.1-informational?style=flat-square) ![AppVersion: 3.0.0](https://img.shields.io/badge/AppVersion-3.0.0-informational?style=flat-square)
```

2023-10-11 18:34 UTC, Jasstkn approved these changes

2023-10-11 18:35 UTC, Jasstkn commented on charts/litmus/values.yaml
> +    customLabels: {}
I prefer `additionalLabels` more but if others are fine, then i doesn't matter much. approving for now.

2023-10-11 19:19 UTC, gdsoumya approved these changes

2023-10-12 12:51 UTC, Calvinaud commented on charts/litmus/values.yaml
> +    customLabels: {}
In the values.yaml all others resource are using `customLabels` (https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/values.yaml#L10) that why I used the same name.

2023-10-12 13:54 UTC, gdsoumya commented on charts/litmus/values.yaml
> +    customLabels: {}
It's probably okay then.

2023-10-12 13:54 UTC, merged