chore: update readme
litmuschaos/litmus-helm pull request #344
Opened 2023-10-23 11:04 UTC by namkyu1999

#### What this PR does / why we need it:
I updated installation.md for ARM users. Briefly, the official MongoDB Helm chart does not support ARM, so I added commands for users to install Litmus with an unofficial MongoDB image.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

2023-10-23 19:41 UTC, Jasstkn reviewed
Hi @namkyu1999! Thank you for your proposed changes. However, I would like to avoid putting some third-party image as officially recommended by Litmus maintainers. 

I think that we can just refer to the original issue: https://github.com/bitnami/charts/issues/7305 and propose an example how to override the image repository and tag via helm values. 

Let me know what do you think about it?

2023-10-24 05:55 UTC, namkyu1999 commented
Hi @Jasstkn, Thanks for the comment.
Let me correct one thing I said. In this installation, We continue to utilize the official MongoDB Helm charts created by Bitnami. But they use `bitnami/mongodb` image by default. So I just override helm values b they` --set` flag like below.

```
helm install chaos litmuschaos/litmus --namespace=litmus \
--set portal.frontend.service.type=NodePort \
--set mongodb.image.registry=ghcr.io/zcube \
--set mongodb.image.repository=bitnami-compat/mongodb \
--set mongodb.image.tag=6.0.5
```

Is this still a non-recommended way?

2023-10-25 11:39 UTC, Jasstkn commented
> Hi @Jasstkn, Thanks for the comment. Let me correct one thing I said. In this installation, We continue to utilize the official MongoDB Helm charts created by Bitnami. But they use `bitnami/mongodb` image by default. So I just override helm values by ` --set` flag like below.
> 
> ```
> helm install chaos litmuschaos/litmus --namespace=litmus \
> --set portal.frontend.service.type=NodePort \
> --set mongodb.image.registry=ghcr.io/zcube \
> --set mongodb.image.repository=bitnami-compat/mongodb \
> --set mongodb.image.tag=6.0.5
> ```
> 
> Is this still a non-recommended way?

I don't want to include in the README recommendation to use specific third-party image. So basically, leave the section with the ARM use-case, add link to the Bitnami issue and add a command like the following:
```bash
helm install chaos litmuschaos/litmus --namespace=litmus \
--set portal.frontend.service.type=NodePort \
--set mongodb.image.registry=<put_registry> \
--set mongodb.image.repository=<put_image_repository> \
--set mongodb.image.tag=<put_image_tag>
```

2023-10-25 13:22 UTC, namkyu1999 commented
Hi @Jasstkn ,
I updated it like below.
```shell
## ARM support
## Litmus Helm Chart depends on bitnami/mongodb, which uses a mongodb image not supported on ARM.
## Use different images and tags as shown below.
# helm install chaos litmuschaos/litmus --namespace=litmus \
# --set mongodb.image.registry=<put_registry> \
# --set mongodb.image.repository=<put_image_repository> \
# --set mongodb.image.tag=<put_image_tag>
```
Can you take a look at this one again, please?

2023-10-26 11:20 UTC, Jonsy13 approved these changes

2023-10-26 11:33 UTC, Jasstkn requested changes

2023-10-26 11:33 UTC, Jasstkn commented on README.md
> +## Litmus helm chart depends on bitnami/mongodb, which uses a mongodb image not supported on ARM.
```suggestion
## Litmus helm chart depends on bitnami/mongodb, which uses a mongodb image that is not build for ARM arch.
## For more details, refer to the issue: https://github.com/bitnami/charts/issues/7305
```

2023-10-26 11:33 UTC, Jasstkn commented on README.md
> +## To install Litmus on an ARM-based server, use a custom MongoDB ARM image instead of the default.
```suggestion
## To install Litmus on an ARM-based machine, you need to provide a custom MongoDB ARM image.
```

2023-10-26 12:18 UTC, Jasstkn approved these changes

2023-10-26 12:18 UTC, merged

2023-10-26 12:19 UTC, Jasstkn commented
@namkyu1999 thank you for the contribution! merged 🚀