Post upgrade hook fix
litmuschaos/litmus-helm pull request #347
Opened 2023-10-30 14:23 UTC by nighthawq7

#### What this PR does / why we need it:
It allows users of this helm chart to opt-out for the post upgrade hook.

#### Which issue this PR fixes
  - fixes 341

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] DCO signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2023-11-01 12:21 UTC, Jasstkn approved these changes
Thanks for the contribution! LGTM. 🚀

2023-11-01 12:21 UTC, Jasstkn commented
@imrajdas @ispeakc0de hey folks. Can I ask you to take a look?

2023-11-03 07:47 UTC, Jasstkn commented
> @imrajdas @ispeakc0de hey folks. Can I ask you to take a look?

ping

2023-11-03 08:00 UTC, nighthawq7 commented
Not sure where to ask, but I see that the chart version is of 3.0.1 on master, but that version have not been released. 
When/What triggers a release of the charts?

2023-11-04 13:15 UTC, Jasstkn commented
> Not sure where to ask, but I see that the chart version is of 3.0.1 on master, but that version have not been released. When/What triggers a release of the charts?

thanks for the report. fixed: https://github.com/litmuschaos/litmus-helm/releases/tag/litmus-3.0.1

2023-11-04 13:21 UTC, gdsoumya requested changes

2023-11-04 13:21 UTC, gdsoumya commented on charts/litmus/values.yaml
> +  enabled: false
The default should be enabled

2023-11-07 13:11 UTC, nighthawq7 commented
@Jasstkn @imrajdas @ispeakc0de 
I'm fairly new to contributing to an open source project. What is the normal lead time to get a pull request through?
To me it seems like a very slow pace at the moment and that will get potential consumer to hesitate to use the tool.

2023-11-07 15:13 UTC, gdsoumya approved these changes
LGTM

2023-11-07 15:13 UTC, gdsoumya commented
@nighthawq7 Thanks for the contribution!

2023-11-07 15:13 UTC, merged