update chart version and values for 3.1.0
litmuschaos/litmus-helm pull request #353
Opened 2023-12-03 23:14 UTC by dwdraju

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2023-12-04 15:23 UTC, Jasstkn requested changes
Hi! Please, check the failed job. I also recommend reading contributing.md if it's your first contribution to this repository. I hope it helps. If not,  ping me up in the commends - I will try to guide you.

2023-12-14 11:28 UTC, imrajdas approved these changes

2023-12-14 14:58 UTC, dwdraju commented
Hi @Jasstkn, can you please review the PR? Thanks!

2023-12-15 07:32 UTC, Jonsy13 approved these changes

2023-12-15 09:22 UTC, Jasstkn approved these changes
LGTM. Thanks!

2023-12-15 09:22 UTC, merged