WIP: [litmus-portal] refactored, added support for different service types and ingress
litmuschaos/litmus-helm pull request #81
Opened 2021-02-23 12:59 UTC by Jasstkn

Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
#### What this PR does / why we need it:
- litmus-portal refactored
- service type for each service is now configurable
- clean up structure of values, names
- added range over variables to leave deployment templates clean
- added ingress for frontend-svc

#### Which issue this PR fixes
  - fixes #79 
  - fixes #80 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2021-02-23 13:29 UTC, Jasstkn commented
Hi! It's a draft for refactoring of litmus-portal changes. Please, check PR description.
Please, advice, if I need to test upgrade from previous version to this one. Because it's possible that it's not possible due to a lot of changes in the immutable objects..

2021-02-25 06:27 UTC, ksatchit commented
I would like to get in @rajdas98 & @gdsoumya 's thoughts here.

2021-03-03 04:58 UTC, gdsoumya commented
The changes look good to me, it would be good if you can post the helm install success logs and also show the pods that come up when the helm chart is installed @Jasstkn .

2021-03-03 05:49 UTC, rajdas98 requested changes

2021-03-03 05:49 UTC, rajdas98 commented on charts/litmus-portal/values.yaml
> +        SUBSCRIBER_IMAGE: "litmuschaos/litmusportal-subscriber:1.13.0"
it's better not to change the env syntax, we are using this format inside out code.

2021-03-03 05:49 UTC, rajdas98 commented on charts/litmus-portal/values.yaml
> +        SUBSCRIBER_IMAGE: "litmuschaos/litmusportal-subscriber:1.13.0"
same for others

2021-03-03 05:49 UTC, rajdas98 commented on charts/litmus-portal/values.yaml
> +  DataBaseServer: "mongodb://litmus-portal-mongo:27017"
For this, you need to change the mongodb service name also

2021-03-03 06:08 UTC, gdsoumya commented on charts/litmus-portal/values.yaml
> +        SUBSCRIBER_IMAGE: "litmuschaos/litmusportal-subscriber:1.13.0"
This change is good @rajdas98 , the env vars we use in the actual server follow the caps format. The changes @Jasstkn has introduced will iterate over these env vars and put them directly into the server deployment as it is, so it should be good.

2021-03-03 06:11 UTC, gdsoumya commented on charts/litmus-portal/values.yaml
> +  DataBaseServer: "mongodb://litmus-portal-mongo:27017"
I think she has updated the db service too https://github.com/Jasstkn/litmus-helm/blob/a375d30bb113e38e41491819cea9d5cc97274961/charts/litmus-portal/templates/mongo-svc.yaml#L4

2021-03-03 19:53 UTC, Jasstkn commented on charts/litmus-portal/values.yaml
> +        SUBSCRIBER_IMAGE: "litmuschaos/litmusportal-subscriber:1.13.0"
Yep, it allows to keep deployment manifest clean and transparent

2021-03-03 19:54 UTC, Jasstkn commented on charts/litmus-portal/values.yaml
> +  DataBaseServer: "mongodb://litmus-portal-mongo:27017"
I think that we can do even better, I'll make a commit.

2021-03-03 20:10 UTC, Jasstkn commented on charts/litmus-portal/values.yaml
> +  DataBaseServer: "mongodb://litmus-portal-mongo:27017"
Done, re-check please :)

2021-03-03 20:16 UTC, Jasstkn commented
> The changes look good to me, it would be good if you can post the helm install success logs and also show the pods that come up when the helm chart is installed @Jasstkn .

```
helm install litmus-portal .
NAME: litmus-portal
LAST DEPLOYED: Wed Mar  3 23:13:37 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing litmus-portal 😀

Your release is named litmus-portal and it's installed to namespace: default.

Visit https://docs.litmuschaos.io/docs/getstarted/ to find more info.


kgp -w
NAME                                     READY   STATUS    RESTARTS   AGE
litmus-portal-frontend-6694f8849-lmbll   1/1     Running   0          2m9s
litmus-portal-mongo-756688bb57-42z4m     1/1     Running   0          2m9s
litmus-portal-server-578bc74b86-f8f8n    2/2     Running   0          35s
```

2021-03-04 07:53 UTC, ksatchit approved these changes

2021-03-04 09:44 UTC, rajdas98 approved these changes

2021-03-04 09:45 UTC, merged