Bug fixing and major refactoring in the litmus-portal helm
litmuschaos/litmus-helm pull request #88
Opened 2021-03-14 20:21 UTC by rajdas98

Bug fixing and major refactoring in the litmus-portal helm

Changes:
- Bugfix in target port of all litmusportal services
- hardcoded server and frontend server because it is hardcoded in litmusportal Nginx file
- changing server and frontend svc to NodePort if ingress is not present
- removing some labels because the service selector is not able to find the pod/deploy using those labels
- removing CRDs as litmusportal will install it after the project creation, if SELF_CLUSTER="true".

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [X] Chart Version bumped
- [ ] Variables are documented in the README.md

2021-03-14 21:03 UTC, Jasstkn reviewed
Why can't we add label instead of removing the standards one?

I also don't understand this change:
> changing server and frontend svc to NodePort if ingress is not present
just make required services configurable with NodePort if needed, but default should be stick with ClusterIP from my point.

2021-03-14 21:09 UTC, rajdas98 commented
> Why can't we add label instead of removing the standards one?
> 
> I also don't understand this change:
> 
> > changing server and frontend svc to NodePort if ingress is not present
> > just make required services configurable with NodePort if needed, but default should be stick with ClusterIP from my point.
There are three cases
1. with ingress- we can make it cluster if we want to use it by the ingress
2. with load balancer- we can access the service using load balancer if we don't want to use ingress
3. with NodePort- this is the last option because we don't want to use ingress or load balancer. 

Also, the load balancer is not available in Minikube Or Kubeadm cluster. That's why we are making NodePort as a default cluster type

2021-03-15 03:42 UTC, ajeshbaby approved these changes
Conditional Approval, For release. Need to refactor with customization for label selection.

2021-03-15 03:43 UTC, ishangupta-ds approved these changes

2021-03-15 03:47 UTC, gdsoumya requested changes

2021-03-15 03:47 UTC, gdsoumya commented on charts/litmus-portal/templates/mongo-sts.yaml
>    name: {{ include "litmus-portal.fullname" . }}-mongo
If the names of the other resources server/frontend are hardcoded we should hardcode the names for other resources too. This can cause confusion later

2021-03-15 03:49 UTC, gdsoumya commented on charts/litmus-portal/templates/mongo-sts.yaml
>    name: {{ include "litmus-portal.fullname" . }}-mongo
Not an urgent change can be done after release

2021-03-15 03:52 UTC, gdsoumya commented on charts/litmus-portal/templates/server-deployment.yaml
> +    component: litmusportal-server
If the names of the other resources frontend/db are dynamic this and others with harcoded names should also be converted.

2021-03-15 03:54 UTC, gdsoumya commented on charts/litmus-portal/templates/server-deployment.yaml
> +    component: litmusportal-server
I see we need the label selector in the code, ignore the above comment.

2021-03-15 04:24 UTC, gdsoumya approved these changes
Merging for release, changes pending will be tracked @rajdas98

2021-03-15 04:24 UTC, merged

2021-03-15 04:26 UTC, ajeshbaby commented
@rajdas98  @gdsoumya Can you put an issue reference to the issue here for tracking

2021-03-15 05:00 UTC, Jasstkn commented
> > Why can't we add label instead of removing the standards one?
> 
> > 
> 
> > I also don't understand this change:
> 
> > 
> 
> > > changing server and frontend svc to NodePort if ingress is not present
> 
> > > just make required services configurable with NodePort if needed, but default should be stick with ClusterIP from my point.
> 
>  
> 
> @Jasstkn - There are three cases
> 
> 1. with ingress- we can make it clusterip if we want to use it by the ingress
> 
> 2. with load balancer- we can access the service using load balancer if we don't want to use ingress
> 
> 3. with NodePort- this is the last option because if we don't want to use ingress or load balancer. 
> 
> 
> 
> Also, the load balancer is not available in Minikube Or Kubeadm cluster. That's why we are making NodePort as a default cluster type

The default service type is clusterIP. We should stick with it in this chart too. It's default because it's safe - it doesn't open any ports, it doesn't require a LB. 
User can access an application using `kubectl port forward` command...

2021-03-15 05:25 UTC, rajdas98 commented
> > > Why can't we add label instead of removing the standards one?
> > 
> > 
> > > 
> > 
> > 
> > > I also don't understand this change:
> > 
> > 
> > > 
> > 
> > 
> > > > changing server and frontend svc to NodePort if ingress is not present
> > 
> > 
> > > > just make required services configurable with NodePort if needed, but default should be stick with ClusterIP from my point.
> > 
> > 
> > @Jasstkn - There are three cases
> > 
> > 1. with ingress- we can make it clusterip if we want to use it by the ingress
> > 2. with load balancer- we can access the service using load balancer if we don't want to use ingress
> > 3. with NodePort- this is the last option because if we don't want to use ingress or load balancer.
> > 
> > Also, the load balancer is not available in Minikube Or Kubeadm cluster. That's why we are making NodePort as a default cluster type
> 
> The default service type is clusterIP. We should stick with it in this chart too. It's default because it's safe - it doesn't open any ports, it doesn't require a LB.
> User can access an application using `kubectl port forward` command...

Hi @Jasstkn, Currently, some of the litmus users are using NodePort. We can move to clusterIP after this release. Is this okay for you?