Chore(Update-CRDs): Update CRDs from v1beta1 to v1 for litmus-portal
litmuschaos/litmus-helm pull request #99
Opened 2021-03-30 15:00 UTC by uditgaurav

Signed-off-by: udit <udit@chaosnative.com>
#### What this PR does / why we need it:

- This PR update the litmus CRDs version from v1beta1 to v1. The change is done for litmus & k8s-chaos crd files. This is done as the v1beta1 is going to depreciate in Kubernetes upcoming releases.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #  https://github.com/litmuschaos/litmus/issues/2613

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] DCO signed
- [X] Chart Version bumped
- [ ] Variables are documented in the README.md

2021-03-30 16:16 UTC, Jasstkn requested changes
Hi! LGTM, but you need to update docs (check failed job, it advices to run helm-docs to autogenerate README regarding your changes).

2021-04-15 17:52 UTC, uditgaurav commented
Thanks @Jasstkn Have run helm-docs.

2021-04-15 18:16 UTC, Jasstkn approved these changes

2021-06-08 16:55 UTC, ksatchit approved these changes

2021-06-08 16:55 UTC, merged